version: '3.8'

services:
  db:
    restart: always
    image: postgres
    env_file: ./backend/.env
    ports:
      - "5432:5432"

  backend:
    restart: always
    build:
      context: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - db
    command: /bin/sh -c "./wait-for-db.sh db flask db upgrade && flask run --host=0.0.0.0 --port=5001"

  bot:
    restart: always
    build:
      context: ./bot
    ports:
      - "5002:5002"

  frontend:
    restart: always
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - bot
      - frontend

volumes:
  db-data:
